---
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
python:
  install:
    - path: .
    - requirements: .rtfd-requirements.txt
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
version: 2
