apps:
  macprefs:
    command: 'bin/macprefs'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/macprefs/issues'
description: 'Command and library to export macOS preferences.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/macprefs/issues'
license: 'MIT'
name: 'macprefs'
parts:
  macprefs:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/macprefs'
summary: 'Command and library to export macOS preferences.'
title: 'macprefs'
version: '0.4.2'
website: 'https://tatsh.github.io/macprefs/'
