---
jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (Poetry)
        run: poetry install --with=dev --with=tests
      - name: Install dependencies (Yarn)
        run: yarn
      - name: Run tests
        run: yarn test
      - if: matrix.python-version == 3.11
        name: Coveralls
        run: poetry run coveralls --service=github
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
name: Tests
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
